### ISSUE TITLE
Fix scikit-learn dependency

### ISSUE THREAD

**Issue by paulduf** [marineLM/NeuMiss_sota#1]
Hello,

Could you please change `sklearn` into `scikit-learn` in the `setup.py` dependencies ? This in turn cause my build to fail.

Error from `scikit-learn` developers is (https://pypi.org/project/sklearn/)
```
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands. 
   
   Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
   - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
   - if the 'sklearn' package is used by one of your dependencies,
     it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
```

**Comment by marineLM** [comment]
Hello,
It should be alright now.
Thanks for reporting.

**Comment by paulduf** [comment]
Sorry to bother you again, but it should be changed also in the [`pyproject.toml`](https://github.com/marineLM/NeuMiss_sota/blob/master/pyproject.toml) (got a failure for another of my project where it seems to rely on this one rather than the `setup.py` !

**Comment by marineLM** [comment]
Done thanks!
